### ISSUE TITLE
React in production

### ISSUE THREAD

**Issue by jaaqo** [vrk-kpa/suomifi-icons#13]
This library depends on React 16.7 and thus by default is bundled with development version of React. For consumption, I think the React should be moved to peerDependencies.

@J-Kallunki

**Comment by J-Kallunki** [comment]
Yeah definitely thank you for noticing. Also I think typings should be devDependencies.
Here they should be right: https://github.com/vrk-kpa/suomifi-ui-components/blob/develop/package.json#L121

**Comment by jaaqo** [comment]
This is also somewhat critical for users of suomifi-ui-components library (like us), because it forcebundles another version of React we do not really need.

**Comment by J-Kallunki** [comment]
> This is also somewhat critical for users of suomifi-ui-components library (like us), because it forcebundles another version of React we do not really need.

Yes we have taken this under work and make releases for both
