### ISSUE TITLE
Typescript error

### ISSUE THREAD

**Issue by atorma** [vrk-kpa/suomifi-icons#83]
With suomifi-icons 7.0.0, I'm getting a Typescript error when I do a type check of my code that imports suomifi-ui-components:

```
node_modules/suomifi-icons/types/src/index.d.ts:214:87 - error TS2307: Cannot find module './IconLists' or its corresponding type declarations.

214 export { baseIcons, illustrativeIcons, doctypeIcons, componentIcons, logoIcons } from './IconLists';
```

**Comment by riitasointi** [comment]
Thanks for the report!

This issue was fixed in the latest patch release 7.0.1
https://github.com/vrk-kpa/suomifi-icons/pull/84
